### ISSUE TITLE
Add a better startup shop config

### ISSUE THREAD

**Issue by andersand** [NexAdn/UnitedShops#2]
Hi, I made a little shop config it's easier to get started with. Maybe add that to the next release?

[config.txt](https://github.com/NexAdn/unitedshops/files/1958332/config.txt)

**Comment by NexAdn** [comment]
Your config file is indeed way better to understand by newbies, so i'll add it, but I'd really appreciate it if you open a pull request next time. Nonetheless, thank you very much.
