### ISSUE TITLE
Problems with wrong textures on dark oak / acacia log

### ISSUE THREAD

**Issue by Nezurro** [NexAdn/UnitedShops#35]
I cant Add Acacia Logs and Dark Oak logs into shop. 
It showns in shop with pink texture. 
I can buy it or sell but when i buy, it shows in my inventory as pink texture, then when i put in into world it transform into Oak Log.
Also it figures in material names as LOG2:0 and LOG2:1 but when i put it into config it makes error, so I used LOG:4 and LOG:5. It works but causes problems written above.

**Comment by NexAdn** [comment]
Could you please provide a snapshot of your `config.yml` and `shops.yml` from the time these errors occured so that I can have a look at them?

**Comment by NexAdn** [comment]
Closed due to inactivity.
